### ISSUE TITLE
running examples using standard python instead of intel 

### ISSUE THREAD

**Issue by petacube** [IntelPython/composability_bench#2]
intel distribution for python have not been updated in 2 years. many packages (eg dask or numpy) or 3-4 releases behind. 
 is it possible to run intel tbb examples using standard python and just installing tbb libraries?

same applies to dask numba and numpy. if  intel made changes to these would it not make sense to submit changes to package maintainers instead of separate forks. just curious

**Comment by anton-malakhov** [comment]
Thank you for submitting the first issue on this repository of threading composability benchmarks.
Unfortunately, it's not clear if it was submitted to the right place or if it uses right terms. But please let me answer to the questions and your assumptions as I understand them.

Intel Distribution for Python is actually regularly updated, at least on the quarterly basis. Please refer to the:
* Intel channel on Anaconda cloud: https://anaconda.org/intel/
* Product home-page: https://software.intel.com/en-us/distribution-for-python
* Forum where the questions about the distribution usually go: https://software.intel.com/en-us/forums/intel-distribution-for-python

We don't ship Dask as part of our distribution, it's just easily installable from the default coda channel. Numpy is pretty up to date, v1.14.3: https://anaconda.org/intel/numpy
All the packages contain recipes with patches we apply against the upstream and we work with the upstream community in order to integrate them, as we already did with Numpy and Numba for example. It just takes time, while Intel needs a faster channel to deliver latest optimizations to its customers.

Now, getting back to the TBB benchmarks-related question, yes, it is possible to run 'standard' python because python interpreter does not play significant role here. `tbb4py` can be installed from intel and conda-forge channels and even with `pip install tbb4py` if your python is of versions 2.7 or 3.6.
In order to observe any benefits from using TBB module, you'll need MKL-based numpy though (Anaconda and Intel have it by default, conda-forge doesn't; also `pip install intel-numpy`). If you want to blend numba into the composability study, you'll need Intel's build of numba as well since it uses TBB for threading.

**Comment by petacube** [comment]
ok i had run this example with monkey patching. i had installed tbbpy. the time is the same. 4 cores on on mac book pro. i have mkl from anaconda. 

i have anaconda with python 3.5

# this is benchmark code 
import dask, time
import dask.array as da

x = da.random.random((10000, 200), chunks=(1000, 200))

t0 = time.time()

 
q, r = da.linalg.qr(x)
test = da.all(da.isclose(x, q.dot(r)))

assert(test.compute()) # compute(get=dask.threaded.get) by default
print(time.time() - t0)

# this are the benchmarks commands
the timing is the same python bench.py
0.45116496086120605

python -m tbb bench.py
0.5128509998321533

**Comment by anton-malakhov** [comment]
4 CPUs is just not enough to expose the oversubscription overheads.
I recently re-acquired performance times on appropriate 2-socket system with 88 CPUs on recent versions of the packages with the benchmarks published in scipy2017/ directory. The results are published now in http://conference.scipy.org/proceedings/scipy2018/pdfs/anton_malakhov.pdf along with deep enough explanation of the issues and the benches.

Running your code within exactly the same environment I used for the paper gives:
```sh
(scipy2018) $ python issue2.py
3.55873966217041
(scipy2018) $ python issue2.py
3.696704387664795
(scipy2018) $ python issue2.py
3.8164076805114746
(scipy2018) $ KMP_BLOCKTIME=0 python issue2.py
0.941957950592041
(scipy2018) $ KMP_BLOCKTIME=0 python issue2.py
1.7893803119659424
(scipy2018) $ KMP_BLOCKTIME=0 python issue2.py
0.6286065578460693
(scipy2018) $ python -m tbb issue2.py
0.22890949249267578
(scipy2018) $ python -m tbb issue2.py
0.22321701049804688
(scipy2018) $ python -m tbb issue2.py
0.22690320014953613
(scipy2018) $ python -m smp issue2.py
0.1791524887084961
(scipy2018) $ python -m smp issue2.py
0.1779646873474121
(scipy2018) $ python -m smp issue2.py
0.16802716255187988
(scipy2018) $ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                88
On-line CPU(s) list:   0-87
Thread(s) per core:    2
Core(s) per socket:    22
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               1200.117
BogoMIPS:              4395.56
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              56320K
NUMA node0 CPU(s):     0-21,44-65
NUMA node1 CPU(s):     22-43,66-87
```
Pretty nice speedup, even better than what we publish in the paper :)

P.S. I noticed that with the recent versions of the packages, `-m tbb` may throw an exception after program completion (`FATAL: exception not rethrown`). That's on my radar already.

**Comment by anton-malakhov** [comment]
I'm closing it for now, please let me know if you still have some questions
